//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bad_Broker_Test_Task.Properties {
    using System.CodeDom.Compiler ;
    using System.Configuration ;
    using System.Diagnostics ;
    using System.Runtime.CompilerServices ;


    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return Settings.defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("USD")]
        public string BaseCurrency {
            get {
                return ((string)(this["BaseCurrency"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("RUB,EUR,GBP,JPY")]
        public string TradingCurrencies {
            get {
                return ((string)(this["TradingCurrencies"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("base={0}")]
        public string BaseCurrencyParameterSpelling {
            get {
                return ((string)(this["BaseCurrencyParameterSpelling"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("symbols={0}")]
        public string TradingCurrenciesParameterSpelling {
            get {
                return ((string)(this["TradingCurrenciesParameterSpelling"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("{0}{1}?{2}&{3}")]
        public string ExchangeRatesRequestPattern {
            get {
                return ((string)(this["ExchangeRatesRequestPattern"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double RequestRatesDaysStep {
            get {
                return ((double)(this["RequestRatesDaysStep"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("http://api.fixer.io/")]
        public string ExchangeRatesDataSource {
            get {
                return ((string)(this["ExchangeRatesDataSource"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(",")]
        public string CurrenciesSeparators {
            get {
                return ((string)(this["CurrenciesSeparators"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(" {0} обмен {1} {2} на {3}, обратный обмен {4} , прибыль {5} ")]
        public string ResultReportPattern {
            get {
                return ((string)(this["ResultReportPattern"]));
            }
        }
    }
}
